name: 테스트 및 빌드

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: JDK 21 설정
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: 테스트 실행
        run: ./gradlew test
        
      - name: 테스트 리포트 저장
        uses: actions/upload-artifact@v3
        if: always() # 테스트 실패해도 리포트 저장
        with:
          name: test-results
          path: build/reports/tests/
          
  build:
    needs: test # 테스트가 성공해야 빌드 진행
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: JDK 21 설정
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: Gradle 빌드
        run: ./gradlew build -x test # 테스트는 이미 했으므로 제외
        
      - name: JAR 파일 저장
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: build/libs/*.jar 